# NOTE: app service is built from the Dockerfile in the current directory.
# The Dockerfile should be set up to install the necessary dependencies and run the application.
# All the dependendencies are saved inside the container, without caching them on the host machine. 

services:
  app:
    build: 
      context: ./services/app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"     # Port for the main application
      - "9229:9229"     # Port for Node.js debugger
    environment:
      - SDF_MAX_UPLOAD_MB=100
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/molecular_app
      - PGDATABASE=molecular_app
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=password
      - PYTHONPATH=/app
      - VIRTUAL_ENV=/venv
      - PATH=/venv/bin:/usr/local/bin:/usr/bin:/bin
    volumes:
      - ./services/app/backup:/app/backup
      - ./services/app/client:/app/client
      - ./services/app/initial_configs:/app/initial_configs
      - ./services/app/server:/app/server
      - ./services/app/shared:/app/shared
      - ./services/app/tests_tools_to_use:/app/tests_tools_to_use
    depends_on:
      db:
        condition: service_healthy
      python-service:
        condition: service_started
    networks:
      - app_network
    restart: unless-stopped
    command: npm run dev:inspect
    # command: npm run dev # Use this command to run without debugger

  python-service:
    build:
      context: ./services/python-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"       # Port for Python service just in debugging. Remove it in production
    volumes:
      - ./services/python-service:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app_network
    restart: unless-stopped
  
  # This uses Postgres’ standard behavior: on first container startup, 
  # if the data directory (/var/lib/postgresql/data) is empty, the official postgres image runs every 
  # *.sql / *.sql.gz / *.sh file in /docker-entrypoint-initdb.d once.
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=molecular_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"       # Port for Postgres database just in debugging. Remove it in production
    volumes:
      - ./services/db/docker_storages/postgres:/var/lib/postgresql/data
      - ./services/db/init/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d molecular_app"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
