# NOTE: app service is built from the Dockerfile in the current directory.
# The Dockerfile should be set up to install the necessary dependencies and run the application.
# All the dependendencies are saved inside the container, without caching them on the host machine. 

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "9229:9229"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/molecular_app
      - PGDATABASE=molecular_app
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=password
      - PYTHONPATH=/app
      - VIRTUAL_ENV=/venv
      - PATH=/venv/bin:/usr/local/bin:/usr/bin:/bin
    volumes:
      - ./backup:/app/backup
      - ./client:/app/client
      - ./initial_configs:/app/initial_configs
      - ./server:/app/server
      - ./shared:/app/shared
      - ./tests_tools_to_use:/app/tests_tools_to_use
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    restart: unless-stopped
    command: npm run dev:inspect
    # command: ["npm", "run", "dev", "--", "--inspect=0.0.0.0:9229"]


  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=molecular_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./docker_storages/postgres:/var/lib/postgresql/data
      - ./initial_configs/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d molecular_app"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
