{ pkgs }: {
  deps = [
    pkgs.gcc12
    pkgs.gccForLibs
    pkgs.zlib
    pkgs.tk
    pkgs.tcl
    pkgs.openjpeg
    pkgs.libxcrypt
    pkgs.libwebp
    pkgs.libtiff
    pkgs.libjpeg
    pkgs.libimagequant
    pkgs.lcms2
    pkgs.freetype
    pkgs.glibcLocales
    pkgs.rapidjson
    pkgs.maeparser
    pkgs.inchi
    pkgs.eigen
    pkgs.coordgenlibs
    pkgs.comic-neue
    pkgs.catch2
    pkgs.cairo
    pkgs.libstdcxx5
    pkgs.libgcc
    pkgs.gcc-unwrapped
    pkgs.gcc
    pkgs.stdenv.cc.cc.lib
    pkgs.glibc
  ];
}