import React, { useState } from 'react';
import { NavigationHeader } from "@/components/navigation-header";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const GuidePage: React.FC = () => {
  const [currentTab, setCurrentTab] = useState("introduction");

  return (
    <div className="min-h-screen bg-lab-bg">
      <NavigationHeader />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
        <div className="mb-8">
          <h1 className="text-3xl font-source font-bold text-gray-900 mb-2 text-center">
            MolVE: Project Guide
          </h1>
          <p className="text-gray-600 text-center">
            Learn how to use MolVE as an admin or evaluator, and how the system is structured under the hood.
          </p>
        </div>

        <Tabs value={currentTab} onValueChange={setCurrentTab} className="space-y-6">
          <TabsList className="grid w-full grid-cols-8">
            <TabsTrigger value="introduction">Overview</TabsTrigger>
            <TabsTrigger value="roles">User Roles</TabsTrigger>
            <TabsTrigger value="admin-workflow">Admin Guide</TabsTrigger>
            <TabsTrigger value="evaluator-workflow">Evaluator Guide</TabsTrigger>
            <TabsTrigger value="api">API</TabsTrigger>
            <TabsTrigger value="features">Features</TabsTrigger>
            <TabsTrigger value="structure">Structure</TabsTrigger>
            <TabsTrigger value="implementation">Implementation</TabsTrigger>
          </TabsList>

          <TabsContent value="introduction">
            <section>
              <h2 className="text-2xl font-semibold mb-4">Project overview</h2>
              <p className="mb-4">
                The rapid progress in artificial intelligence (AI) and machine learning (ML) has profoundly reshaped the landscape of molecular design and drug discovery. MolVE is a web-based, open-source platform designed to support the manual evaluation of molecular candidates generated by AI systems. By providing a secure, collaborative, and interactive environment, MolVE bridges the gap between high-throughput AI-based molecular generation and expert-driven evaluation.
              </p>
              <p>
                The platform enables experts to examine molecular structures in both 2D and 3D, manage datasets, and collaborate effectively. It is built using modern, reliable technologies to ensure scalability, ease of use, and adaptability across academic and industrial environments.
              </p>
              <p className="mt-4">
                This guide is split into practical, task-oriented sections. If you are just trying MolVE for the first time, start with <strong>User Roles</strong>, then follow the <strong>Admin Guide</strong> or <strong>Evaluator Guide</strong> tabs depending on your role. The other tabs explain the API, system features, implementation, and folder structure.
              </p>
            </section>
          </TabsContent>

          <TabsContent value="roles">
            <section>
              <h2 className="text-2xl font-semibold mb-4">User roles</h2>
              <p className="mb-4">
                MolVE distinguishes between two main roles. Knowing your role helps you follow the right part of this guide:
              </p>
              <ul className="list-disc list-inside mb-4 space-y-1">
                <li>
                  <strong>Admin</strong> – can create and manage users, configure evaluation settings, upload and organise molecular datasets, and monitor overall activity.
                </li>
                <li>
                  <strong>Evaluator</strong> – can log in, browse assigned molecules, visualise them in 2D/3D, and submit evaluations (scores and comments).
                </li>
              </ul>
              <p>
                If you are setting up MolVE for a new team or experiment, you will normally start as an admin. You will then create accounts for other evaluators who will use the evaluation interface.
              </p>
            </section>
          </TabsContent>

          <TabsContent value="admin-workflow">
            <section>
              <h2 className="text-2xl font-semibold mb-4">Admin guide</h2>
              <p className="mb-4">
                This section explains, step by step, how an admin uses the interface to configure a study, create users, and make molecules available for evaluation.
              </p>

              <h3 className="text-xl font-semibold mt-4 mb-2">1. Log in as admin</h3>
              <ol className="list-decimal list-inside mb-4 space-y-1">
                <li>Open the MolVE web application in your browser.</li>
                <li>You should see the login screen. Enter your admin credentials (username and password).</li>
                <li>Click the login button. You will be redirected to the main dashboard.</li>
              </ol>

              <h3 className="text-xl font-semibold mt-4 mb-2">2. Open the admin dashboard</h3>
              <ol className="list-decimal list-inside mb-4 space-y-1">
                <li>After logging in, you land on the dashboard. If there is a navigation bar, look for a section like *Admin*, *Dashboard*, or *Settings*.</li>
                <li>The dashboard typically shows high-level statistics (number of users, molecules, sessions, etc.). From here you can access user management and dataset management.</li>
              </ol>

              <h3 className="text-xl font-semibold mt-4 mb-2">3. Create a new user</h3>
              <p className="mb-2">
                To add a new evaluator (or another admin), follow these steps. The exact labels may vary slightly depending on your version of the UI, but the workflow is the same:
              </p>
              <ol className="list-decimal list-inside mb-4 space-y-1">
                <li>From the dashboard, open the *Users* or *User management* section.</li>
                <li>Click the *New user* or *Add user* button.</li>
                <li>Fill in the user details in the form:
                  <ul className="list-disc list-inside ml-6 mt-1 space-y-1">
                    <li><strong>Username</strong> – a unique identifier used for login.</li>
                    <li><strong>Display name</strong> (optional) – human‑readable name shown in the UI.</li>
                    <li><strong>Password</strong> – temporary or permanent password for the user.</li>
                    <li><strong>Role</strong> – choose *evaluator* for someone who will rate molecules, or *admin* if they should also manage the system.</li>
                    <li><strong>Other fields</strong> (if present) – for example, team, study, or notes to identify the user.</li>
                  </ul>
                </li>
                <li>Click the save or create button. The new user appears in the users list.</li>
                <li>Share the login information (username and password) securely with the new user.</li>
              </ol>

              <h3 className="text-xl font-semibold mt-4 mb-2">4. Upload or configure datasets</h3>
              <p className="mb-2">
                Once users exist, the next step is to make molecules available for evaluation:
              </p>
              <ol className="list-decimal list-inside mb-4 space-y-1">
                <li>Navigate to the *Molecules*, *Datasets*, or *Library* section in the admin area.</li>
                <li>Use the upload or import function to add new molecules (for example, via SDF files, CSV, or other supported formats, depending on your deployment).</li>
                <li>Confirm that the imported molecules appear in the list, with identifiers and any metadata (e.g., SMILES, IDs, tags).</li>
              </ol>

              <h3 className="text-xl font-semibold mt-4 mb-2">5. Configure evaluation sessions</h3>
              <p className="mb-2">
                Evaluations are typically organized into sessions or experiments. As an admin you can define which molecules are shown to which users and what questions they answer:
              </p>
              <ol className="list-decimal list-inside mb-4 space-y-1">
                <li>Open the *Sessions* or *Settings* section.</li>
                <li>Create a new evaluation session or study and give it a descriptive name.</li>
                <li>Select or assign the set of molecules that belong to this session.</li>
                <li>Optionally assign which users (or groups of users) should evaluate this session.</li>
                <li>Adjust any evaluation settings available in your deployment (for example: rating scales, required fields, number of molecules per session, randomisation options).</li>
                <li>Save the configuration. Evaluators will now see the assigned molecules when they log in.</li>
              </ol>

              <h3 className="text-xl font-semibold mt-4 mb-2">6. Monitor progress</h3>
              <ol className="list-decimal list-inside mb-4 space-y-1">
                <li>From the dashboard or a dedicated *Reports*/*Statistics* section, monitor how many molecules have been evaluated and by whom.</li>
                <li>Use this information to decide when to close a session or invite more evaluators.</li>
              </ol>
            </section>
          </TabsContent>

          <TabsContent value="evaluator-workflow">
            <section>
              <h2 className="text-2xl font-semibold mb-4">Evaluator guide</h2>
              <p className="mb-4">
                This section explains how an evaluator uses MolVE to inspect molecules and submit evaluations.
              </p>

              <h3 className="text-xl font-semibold mt-4 mb-2">1. Log in</h3>
              <ol className="list-decimal list-inside mb-4 space-y-1">
                <li>Open the MolVE web application in your browser.</li>
                <li>Enter the username and password given to you by an admin.</li>
                <li>Click the login button. You will be redirected to your evaluator dashboard or directly to the evaluation screen.</li>
              </ol>

              <h3 className="text-xl font-semibold mt-4 mb-2">2. Open an evaluation session</h3>
              <ol className="list-decimal list-inside mb-4 space-y-1">
                <li>If you see a dashboard, choose an available *Session* or *Task* from the list.</li>
                <li>Click on the session name to start evaluating its molecules.</li>
              </ol>

              <h3 className="text-xl font-semibold mt-4 mb-2">3. Use the molecular viewer</h3>
              <p className="mb-2">
                The evaluation screen typically shows a viewer and controls:
              </p>
              <ul className="list-disc list-inside mb-4 space-y-1">
                <li><strong>2D view (ChemDoodle)</strong> – displays the molecule in a flat representation. You can inspect bonds, rings, and functional groups.</li>
                <li><strong>3D view (JSmol)</strong> – allows rotation, zoom, and alternative renderings (ball‑and‑stick, wireframe, etc.) to inspect spatial arrangement.</li>
                <li><strong>Navigation controls</strong> – buttons or keyboard shortcuts for *Next* and *Previous* molecule.</li>
                <li><strong>Molecule metadata</strong> – IDs, SMILES, or other properties configured by the admin.</li>
              </ul>

              <h3 className="text-xl font-semibold mt-4 mb-2">4. Fill in the evaluation form</h3>
              <ol className="list-decimal list-inside mb-4 space-y-1">
                <li>For each molecule, use the provided fields to give your assessment. Typical fields include:
                  <ul className="list-disc list-inside ml-6 mt-1 space-y-1">
                    <li><strong>Overall rating</strong> – a numeric score (e.g. 1–5) representing your overall judgement.</li>
                    <li><strong>Specific criteria</strong> – for example, synthesizability, novelty, or drug‑likeness, depending on how the admin configured the session.</li>
                    <li><strong>Comments</strong> – free‑text feedback to capture qualitative insights, caveats, or hypotheses.</li>
                  </ul>
                </li>
                <li>Ensure you complete all required fields (usually marked with an asterisk).</li>
                <li>Click the save or submit button for that molecule before navigating to the next one.</li>
              </ol>

              <h3 className="text-xl font-semibold mt-4 mb-2">5. Move between molecules</h3>
              <ol className="list-decimal list-inside mb-4 space-y-1">
                <li>Use the *Next* button to move forward and *Previous* to revisit earlier molecules.</li>
                <li>If the interface shows a progress bar or counter, use it to track how many molecules you have already evaluated.</li>
                <li>You can usually revisit and update an evaluation if you notice a mistake, as long as the session remains open.</li>
              </ol>

              <h3 className="text-xl font-semibold mt-4 mb-2">6. Finish your session</h3>
              <ol className="list-decimal list-inside mb-4 space-y-1">
                <li>Once you have evaluated all assigned molecules, check that the session progress shows 100% (or that there are no remaining molecules listed as pending).</li>
                <li>Inform the admin if the session required explicit confirmation of completion.</li>
                <li>Log out using the logout button in the navigation bar when you are done.</li>
              </ol>
            </section>
          </TabsContent>

          <TabsContent value="api">
            <section>
              <h2 className="text-2xl font-semibold mb-4">API overview</h2>
              <p className="mb-4">
                The MolVE backend exposes a small HTTP API used by the web interface and, optionally, by external tools. The exact base URL depends on your deployment (for example, <code>/api</code> or a dedicated sub‑path behind a reverse proxy).
              </p>
              <p className="mb-4">
                At a high level, the API groups endpoints into four areas:
              </p>
              <ul className="list-disc list-inside mb-4 space-y-1">
                <li><strong>Authentication</strong> – login and logout endpoints that create and destroy user sessions.</li>
                <li><strong>Users</strong> – endpoints for listing, creating, and updating users (typically restricted to admins).</li>
                <li><strong>Molecules and datasets</strong> – endpoints to list molecules, search by identifiers, and manage datasets.</li>
                <li><strong>Evaluations</strong> – endpoints to create, update, and retrieve evaluation records.</li>
              </ul>
              <p className="mb-4">
                All endpoints follow a JSON‑based request/response style. For authenticated routes, the server expects either a session cookie (for browser use) or an API token (for programmatic access) sent in the <code>X-API-Token</code> header. Error responses include an HTTP status code and a small JSON body describing what went wrong.
              </p>

              <h3 className="text-xl font-semibold mt-4 mb-2">Roles and access levels</h3>
              <p className="mb-2">
                Below is a non‑exhaustive list of important endpoints and who can use them:
              </p>
              <ul className="list-disc list-inside mb-4 space-y-1">
                <li><code>POST /api/v1/molecules</code> – create a single molecule. <strong>Admin API token only</strong>.</li>
                <li><code>POST /api/v1/molecules/upload-sdf</code> – bulk upload molecules from SDF. <strong>Admin API token only</strong>.</li>
                <li><code>GET /api/v1/molecules/download-sdf</code> – download all stored molecules as SDF. <strong>Any valid API token</strong>.</li>
                <li><code>GET /api/v1/molecules/download-csv</code> – download all stored molecules as CSV. <strong>Any valid API token</strong>.</li>
                <li><code>GET /api/v1/evaluations/download-csv</code> – download the full evaluations dataset (including flags and metadata). <strong>Admin API token only</strong>.</li>
              </ul>

              <p className="mb-4">
                For a complete and always‑up‑to‑date list of routes, consult <code>server/routes.ts</code> in the repository. That file shows all paths, required roles, and payload structures.
              </p>

              <h3 className="text-xl font-semibold mt-4 mb-2">Using the API from Python</h3>
              <p className="mb-2">
                Admins can create API tokens in the web UI and then use them with external scripts. The example below shows how to download the molecules dataset as CSV using Python and the <code>requests</code> library:
              </p>
              <pre className="bg-gray-100 text-sm p-4 rounded mb-4 overflow-x-auto">
<code>{`import requests

BASE_URL = "http://localhost:3000"  # adjust to your deployment
API_TOKEN = "YOUR_API_TOKEN_HERE"   # create this in the MolVE UI

headers = {
    "X-API-Token": API_TOKEN,
}

resp = requests.get(
    f"{BASE_URL}/api/v1/molecules/download-csv",
    headers=headers,
    timeout=60,
)

resp.raise_for_status()  # raise an error if the request failed

with open("molecules_dataset.csv", "wb") as f:
    f.write(resp.content)

print("Saved CSV with status:", resp.status_code)`}</code>
              </pre>
              <p>
                You can adapt the same pattern to call other endpoints, for example <code>/api/v1/evaluations/download-csv</code> (admin token required) or <code>/api/v1/molecules</code> to programmatically register new molecules.
              </p>
            </section>
          </TabsContent>

          <TabsContent value="features">
            <section>
              <h2 className="text-2xl font-semibold mb-4">Key features</h2>
              <p className="mb-4">MolVE offers the following main capabilities:</p>
              <ul className="list-disc list-inside mb-4">
                <li><strong>Secure authentication</strong> – login‑based access control with separate admin and evaluator roles.</li>
                <li><strong>Admin dashboard</strong> – overview of users, datasets, and evaluation activity.</li>
                <li><strong>Interactive molecular visualisation</strong> – 2D and 3D viewers powered by ChemDoodle and JSmol.</li>
                <li><strong>Evaluation interface</strong> – structured forms for collecting scores and comments on each molecule.</li>
                <li><strong>Dataset management</strong> – tools to upload, organise, and maintain molecular datasets.</li>
              </ul>
            </section>
          </TabsContent>

          <TabsContent value="structure">
            <section>
              <h2 className="text-2xl font-semibold mb-4">Project structure</h2>
              <p className="mb-4">The repository is organised into a few main directories:</p>
              <ul className="list-disc list-inside mb-4">
                <li><strong>src/</strong> – main frontend application code, including components, hooks, pages, and utilities.</li>
                <li><strong>server/</strong> – backend logic, including authentication, database access, and API routes.</li>
                <li><strong>client/</strong> – static assets and third‑party libraries such as ChemDoodle and JSmol.</li>
                <li><strong>shared/</strong> – shared schemas and types used by both client and server.</li>
                <li><strong>tests_tools_to_use/</strong> – testing tools and support files.</li>
              </ul>
            </section>
          </TabsContent>

          <TabsContent value="implementation">
            <section>
              <h2 className="text-2xl font-semibold mb-4">Implementation details</h2>
              <p className="mb-4">
                MolVE is implemented as a full‑stack web application using a modern TypeScript‑based toolchain:
              </p>
              <ul className="list-disc list-inside mb-4">
                <li><strong>Frontend</strong> – React with TypeScript and Tailwind CSS for a responsive, component‑based UI.</li>
                <li><strong>Backend</strong> – Node.js and Express, with PostgreSQL as the primary database.</li>
                <li><strong>Data access</strong> – Drizzle ORM for type‑safe queries and migrations.</li>
                <li><strong>Authentication</strong> – Passport and <code>express-session</code> for session‑based login.</li>
                <li><strong>Deployment</strong> – Docker and Docker Compose for reproducible, containerised deployment.</li>
              </ul>
            </section>
          </TabsContent>

        </Tabs>
      </div>
    </div>
  );
};

export default GuidePage;