import React, { useState } from 'react';
import { NavigationHeader } from "@/components/navigation-header";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const GuidePage: React.FC = () => {
  const [currentTab, setCurrentTab] = useState("introduction");

  return (
    <div className="min-h-screen bg-lab-bg">
      <NavigationHeader />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
        <div className="mb-8">
          <h1 className="text-3xl font-source font-bold text-gray-900 mb-2 text-center">
            MolVE: Project Guide
          </h1>
          <p className="text-gray-600 text-center">
            Learn about the structure, features, and implementation of the MolVE platform.
          </p>
        </div>

        <Tabs value={currentTab} onValueChange={setCurrentTab} className="space-y-6">
          <TabsList className="grid w-full grid-cols-5">
            <TabsTrigger value="introduction">Introduction</TabsTrigger>
            <TabsTrigger value="folder-structure">Folder Structure</TabsTrigger>
            <TabsTrigger value="features">Features</TabsTrigger>
            <TabsTrigger value="implementation">Implementation</TabsTrigger>
            <TabsTrigger value="getting-started">Getting Started</TabsTrigger>
          </TabsList>

          <TabsContent value="introduction">
            <section>
              <h2 className="text-2xl font-semibold mb-4">Introduction</h2>
              <p className="mb-4">
                The rapid progress in artificial intelligence (AI) and machine learning (ML) has profoundly reshaped the landscape of molecular design and drug discovery. MolVE is a web-based, open-source platform designed to support the manual evaluation of molecular candidates generated by AI systems. By providing a secure, collaborative, and interactive environment, MolVE bridges the gap between high-throughput AI-based molecular generation and expert-driven evaluation.
              </p>
              <p>
                The platform enables experts to examine molecular structures in both 2D and 3D, manage datasets, and collaborate effectively. It is built using modern, reliable technologies to ensure scalability, ease of use, and adaptability across academic and industrial environments.
              </p>
            </section>
          </TabsContent>

          <TabsContent value="folder-structure">
            <section>
              <h2 className="text-2xl font-semibold mb-4">Folder Structure</h2>
              <p className="mb-4">The project is organized into the following key directories:</p>
              <ul className="list-disc list-inside mb-4">
                <li><strong>src/</strong>: Contains the main application code, including components, hooks, pages, and utilities.</li>
                <li><strong>server/</strong>: Handles backend logic, including authentication, database interactions, and API routes.</li>
                <li><strong>client/</strong>: Includes client-side assets such as HTML templates and third-party libraries.</li>
                <li><strong>shared/</strong>: Contains shared code, such as schemas and types, used across the application.</li>
                <li><strong>tests_tools_to_use/</strong>: Provides testing tools and resources for the application.</li>
              </ul>
            </section>
          </TabsContent>

          <TabsContent value="features">
            <section>
              <h2 className="text-2xl font-semibold mb-4">Features</h2>
              <p className="mb-4">MolVE offers the following key features:</p>
              <ul className="list-disc list-inside mb-4">
                <li><strong>Secure User Authentication:</strong> Ensures data protection and accountability.</li>
                <li><strong>Admin Dashboard:</strong> Provides an overview of system statistics, user management, and dataset control.</li>
                <li><strong>Interactive Molecular Visualization:</strong> Enables 2D and 3D manipulation of molecular structures using JSmol and ChemDoodle.</li>
                <li><strong>Evaluation Interface:</strong> Allows structured feedback with qualitative ratings and optional comments.</li>
                <li><strong>Dataset Management:</strong> Supports uploading, removing, and organizing molecular datasets.</li>
              </ul>
            </section>
          </TabsContent>

          <TabsContent value="implementation">
            <section>
              <h2 className="text-2xl font-semibold mb-4">Implementation Details</h2>
              <p className="mb-4">
                The platform is a full-stack solution built with modern technologies:
              </p>
              <ul className="list-disc list-inside mb-4">
                <li><strong>Frontend:</strong> Built with React and styled using Tailwind CSS for a responsive and modular user interface.</li>
                <li><strong>Backend:</strong> Powered by Node.js and Express, with PostgreSQL as the database and Drizzle ORM for type-safe database interactions.</li>
                <li><strong>Authentication:</strong> Managed using Passport and express-session for secure user sessions.</li>
                <li><strong>Deployment:</strong> Containerized with Docker and Docker Compose for consistent and scalable deployment.</li>
              </ul>
            </section>
          </TabsContent>

          <TabsContent value="getting-started">
            <section>
              <h2 className="text-2xl font-semibold mb-4">Getting Started</h2>
              <p className="mb-4">To set up and run the project, follow these steps:</p>
              <ol className="list-decimal list-inside mb-4">
                <li>Install dependencies using <code>npm install</code> or <code>pip install -r requirements.txt</code>.</li>
                <li>Set up the database by running the initialization scripts in the <code>initial_configs/</code> directory.</li>
                <li>Start the development server using <code>npm run dev</code>.</li>
              </ol>
              <p>
                For more detailed information, refer to the documentation in the respective directories.
              </p>
            </section>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
};

export default GuidePage;